package com.travelapp.config

import com.travelapp.sdk.config.CornerType
import com.travelapp.sdk.config.AppTabs
import com.travelapp.sdk.config.EnabledInfoItems
import com.travelapp.sdk.config.IconsType
        
/**
* Do not modify! Auto generated by 'parseConfig' task
*/
object WhiteLabelConf {

    const val host: String = "com.www.avia.kg.app"
    
    const val apiKey: String = "806576197210fa8b89ffa4afbd140dd8"

    const val email: String = "https://wa.me/996777505707"

    const val appVerison: String = "1.2.4"

    const val appId: String = "com.www.avia.kg.app"
    
    val marker: Int = 564205
    
    val clientDeviceHost: String = "android.apartments"

    val flightsTabEnabled: Boolean = true
    
    val hotelsTabEnabled: Boolean = true

    const val sharingLink: String = ""

    const val handlingLink: String = ""

    const val appsflyerDevKey: String = ""

    object Style {
        val cornerType: CornerType = CornerType.getByName("round")
        val iconsType: IconsType = IconsType.getByName("tint")
    }
    
    object InfoConfig {
        val enabledItems: Set<EnabledInfoItems> = setOf<EnabledInfoItems?>(
            EnabledInfoItems.getByName("about_app"), EnabledInfoItems.getByName("rate_app"), EnabledInfoItems.getByName("share_app")
        ).filterNotNull().toSet()
    }

    object Advertising {
        const val appodealApiKey: String = ""

        object Placements {
            const val airTicketPlacementInterstitial: String = ""

            const val airTicketPlacementBanner: String = ""

            const val hotelsPlacementInterstitial: String = ""

            const val hotelsPlacementBanner: String = ""

        }
    }




    
    

    
}